data_configs:
    train_path: "datasets/utn_dataset_curated/part2/train"
    val_path: "datasets/utn_dataset_curated/part2/val"
    test_path: "datasets/utn_dataset_curated/part2/test"
    preprocessing_related: 
        mean: 0.5 # for raw_image normalisation
        std: 0.5 # for raw_image normalisation
    augmentation_related:
        place_holder: None # this is just a place holder, will be filled later

model_configs:
    epochs: 1
    batch_size: 32
    device: "cuda" # either "cpu" or "cuda"
    backbone:
        name: VGG16
        num_stages: 6
    loss_function_related:
        alpha: 1 # loss = alpha*loc_loss + cls_loss
        pos_box_threshold: 0.5 # a default box is marked positive if it has (> pos_box_threshold) IoU score with any of the groundtruth boxes
        hard_neg_pos: 3 # num of negative boxes = hard_neg_pos * num_positive_boxes
    optim:
        name: SGD
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0005
    scheduler:
        name: MultiStepLR
        milestones: [155, 195]
        gamma: 0.1

task_configs:
    log_expt: False # whether to log the experiment online or not
    num_classes: 37 # A-Z(26), 0-9(10), background(1)
    min_cls_score: 0.01 # if the cls score for a bounding box is less than this, it is considered as background
    nms_iou_score: 0.1 # if the iou between two bounding boxes is less than this, it is suppressed